services:
  wordpress:
    build: .
    container_name: wordpress_community
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_community_malik
      WORDPRESS_DB_USER: malik123
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_DATABASE: wordpress_community_malik
      MYSQL_USER: malik123
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
      - ./db.opt:/etc/mysql/conf.d/db.opt
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge
